# Cloud Build CI/CD Pipeline
# Triggered by: Push to main/master branch
# Flow: Test → Build → Deploy to Cloud Run → Update API Gateway (if changed)

steps:
  # Step 1: Install dependencies and run tests
  - name: 'python:3.11-slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "📦 Installing dependencies..."
        pip install uv --quiet
        uv pip install --system -e ".[dev]" --quiet
        
        echo "🧪 Running tests..."
        pytest tests/ -v --cov=src/mcp_server --cov-report=term
    id: 'run-tests'
    env:
      - 'PYTHONPATH=/workspace/src'

  # Step 2: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-image'
    waitFor: ['run-tests']

  # Step 3: Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 4: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "🚀 Deploying to Cloud Run..."
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "GCS_BUCKET=${_GCS_BUCKET},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION},GCP_PROJECT_ID=$PROJECT_ID" \
          --memory ${_MEMORY} \
          --cpu ${_CPU} \
          --timeout ${_TIMEOUT} \
          --max-instances ${_MAX_INSTANCES} \
          --min-instances ${_MIN_INSTANCES} \
          --tag ${_ENVIRONMENT} \
          --quiet
        
        echo "✅ Deployment complete!"
    id: 'deploy-cloudrun'
    waitFor: ['push-image']

  # Step 6: Get Cloud Run service URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region ${_REGION} \
          --format 'value(status.url)')
        echo "$SERVICE_URL" > /workspace/service_url.txt
        echo "📍 Service URL: $SERVICE_URL"
    id: 'get-service-url'
    waitFor: ['deploy-cloudrun']

  # Step 7: Health check
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: bash
    args:
      - '-c'
      - |
        SERVICE_URL=$(cat /workspace/service_url.txt)
        
        echo "🏥 Running health check on $SERVICE_URL/health"
        
        for i in {1..10}; do
          if curl -f "$SERVICE_URL/health" -o /dev/null -s -w "Status: %{http_code}\n"; then
            echo "✅ Health check passed!"
            exit 0
          fi
          echo "⏳ Attempt $i/10 failed, retrying in 5s..."
          sleep 5
        done
        
        echo "❌ Health check failed after 10 attempts"
        exit 1
    id: 'health-check'
    waitFor: ['deploy-cloudrun']

  # Step 8: Check if API Gateway config changed
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args:
      - '-c'
      - |
        # For initial commit or if we can't get diff, assume changed
        if git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -q "api-gateway-config.yaml"; then
          echo "true" > /workspace/gateway_changed.txt
          echo "⚠️  API Gateway config changed - will update"
        else
          echo "false" > /workspace/gateway_changed.txt
          echo "✅ API Gateway config unchanged - skipping update"
        fi
    id: 'check-gateway-changes'
    waitFor: ['health-check']

  # Step 9: Update API Gateway config (only if changed)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        GATEWAY_CHANGED=$(cat /workspace/gateway_changed.txt)
        SERVICE_URL=$(cat /workspace/service_url.txt)
        
        if [ "$GATEWAY_CHANGED" = "true" ] && [ "${_UPDATE_GATEWAY}" = "true" ]; then
          echo "🔧 Updating API Gateway configuration..."
          
          # Replace placeholders in config
          sed -i "s|https://constructio-mcp-server-XXXXXX.a.run.app|$SERVICE_URL|g" api-gateway-config.yaml
          sed -i "s|YOUR_PROJECT_ID|$PROJECT_ID|g" api-gateway-config.yaml
          
          # Create new API config
          CONFIG_NAME="${_API_ID}-config-$SHORT_SHA"
          
          echo "Creating API config: $CONFIG_NAME"
          gcloud api-gateway api-configs create $CONFIG_NAME \
            --api=${_API_ID} \
            --openapi-spec=api-gateway-config.yaml \
            --project=$PROJECT_ID \
            --display-name="Auto-deployed from commit $SHORT_SHA" \
            --quiet || echo "⚠️  Config creation failed (may already exist)"
          
          # Update gateway to use new config
          echo "Updating gateway: ${_GATEWAY_ID}"
          gcloud api-gateway gateways update ${_GATEWAY_ID} \
            --api=${_API_ID} \
            --api-config=$CONFIG_NAME \
            --location=${_REGION} \
            --project=$PROJECT_ID \
            --quiet
          
          # Get gateway URL
          GATEWAY_URL=$(gcloud api-gateway gateways describe ${_GATEWAY_ID} \
            --location=${_REGION} \
            --format='value(defaultHostname)' 2>/dev/null || echo "N/A")
          
          echo "✅ API Gateway updated!"
          echo "🌐 Gateway URL: https://$GATEWAY_URL"
        else
          if [ "${_UPDATE_GATEWAY}" = "false" ]; then
            echo "⏭️  Gateway update disabled via _UPDATE_GATEWAY=false"
          else
            echo "⏭️  Skipping API Gateway update (no changes detected)"
          fi
        fi
    id: 'update-api-gateway'
    waitFor: ['check-gateway-changes']

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Substitution variables
# Set these in Cloud Build trigger or override via: --substitutions KEY=VALUE
substitutions:
  # Service configuration
  _SERVICE_NAME: 'constructio-mcp-server'
  _REGION: 'us-central1'
  _ENVIRONMENT: 'production'
  
  # Cloud Run resources
  _MEMORY: '512Mi'
  _CPU: '1'
  _TIMEOUT: '300'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '0'
  
  # Application configuration
  _GCS_BUCKET: 'your-bucket-name'  # REQUIRED: Set in trigger
  _FIRESTORE_COLLECTION: 'generators'
  
  # API Gateway configuration
  _UPDATE_GATEWAY: 'true'  # Set to 'false' to skip gateway updates
  _API_ID: 'constructio-api'
  _GATEWAY_ID: 'constructio-gateway'

# Build configuration
options:
  machineType: 'N1_HIGHCPU_8'  # Faster builds
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'  # Allow undefined substitutions in non-critical places

# Timeout for entire build
timeout: '1200s'  # 20 minutes
